### ISSUE TITLE
R4 Chips and board

### ISSUE THREAD

**Issue by Juanito9001** [kitling/flashcart_core#15]
I want in this post, everyone post photos about their R4´s chip, i want to do a physical comparisson of all the families (r4ids.cn, r4i-sdhc.com, r4isdhc.com, r4igold.cn, r4igold.cc, etc) maybe with this, we can found a relation between the funcional and supported and the actually unsupported

**Comment by dentnz** [comment]
http://r4igold.cc/3ds_product.asp <- this is what my R4iGold.cc flash cart looks like...

**Comment by Juanito9001** [comment]
![20170815_211402](https://user-images.githubusercontent.com/27431883/29344663-11a87b7e-81ff-11e7-9782-d5b231fc060c.jpg)
![20170815_211350](https://user-images.githubusercontent.com/27431883/29344661-11a11776-81ff-11e7-9dd9-f04aaf7db125.jpg)
![20170815_211356](https://user-images.githubusercontent.com/27431883/29344662-11a1b6f4-81ff-11e7-8f57-b099d464c7b3.jpg)

**Comment by moodswingsthelad** [comment]
![](http://i.imgur.com/7pwdoTT.jpg)
This is mine.

_Sent from my Samsung GT-I9505 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SammyAsia** [comment]
![r4isdhcdualcore](https://user-images.githubusercontent.com/31177950/29493263-37c08436-8593-11e7-9f6b-21c9627a363f.jpg)
