### ISSUE TITLE
R4I-ADVANCE 1.6

### ISSUE THREAD

**Issue by Juanito9001** [kitling/flashcart_core#18]
Somebody Knows if the R4i-advance 1.6 works with ntrboot?

https://3.imimg.com/data3/LK/NU/MY-8936786/r4i-advance-with-60-best-games-500x500.jpg

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hedgeberg** [comment]
Do you have one of these cards? Can you submit a picture of the pcb, as well as the chip id and the hw rev?

**Comment by Juanito9001** [comment]
The card is from a friend, in this days i upload a photo with the pcb and info from the nrtboot

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hedgeberg** [comment]
From now on please do not submit an issue until you've got this info.

**Comment by AliQ84** [comment]
HELLO
i download revolotion from 2 link (archive . org and linfoxdomain . com) but i have white screen on NDS Lite
i am test 5 Memory Cards (1GB-2GB-4GB-8GB and 32GB) & 4 NDS Lite Consoles & 4 R4i advance Cards & Format memory Cards (fat32-fat16-fat-exfat-ntsf) & default-16-32.... unit size...
pleaes HELP me :)
THANX
