### ISSUE TITLE
3DSi R4Gold.cc Upgradable common site still active

### ISSUE THREAD

**Issue by sergiogamboa2** [kitling/flashcart_core#22]
So I have since the 2013 this cart  for the DSi and 3DS the firmware upgrades (latest v7.0) is still in the site active this are really really common in Costa Rica since the reseller mostly brought this carts here. I will add some more info if you decide to plan this to release in the netboot Flasher (hope you can because it is really complicated to buy one of the other sites) 

I used the NTRBoot Flasher 0.1.2

If there is a way to force the flasher to flash the cart please tell me even if I lose the flashcard functionality in CR is also common a gateway DSi cart so I have 2 however the gateway one says chip ID 00000FC2 and HW Rev 00000000

http://r4igold.cc/3ds_main.asp

![screen shot 2017-08-22 at 14 08 54](https://user-images.githubusercontent.com/24198611/29585272-c8b9bf82-8743-11e7-8ee1-ad94435b4b9b.png)

![img_2070](https://user-images.githubusercontent.com/24198611/29585311-eb2ad574-8743-11e7-9539-64fb993c699c.JPG)
![img_8899](https://user-images.githubusercontent.com/24198611/29585313-eb54df90-8743-11e7-9e77-9ac2c2f07450.JPG)
![img_9620](https://user-images.githubusercontent.com/24198611/29585312-eb471e6e-8743-11e7-99d0-64675d37c8ee.JPG)

latest 3DSi R4Gold.cc firmware and the DSmenu rpg
[https://mega.nz/#!5x1X2IZD!kNUSE6jvgWYzdUACJvh6MFAYoappxFVUBXZsw7zV-Pw](url)

**Comment by Juanito9001** [comment]
I'm with the same problem... using the R4i gold wood, i want to force the flash (i dont care if the flashcart funtion will lost, i only need it to do the magnethax)
ChipID: 00000FC2
HWrev: A5A5A5A5
R4IGOLD.CC

and the weird thing is... some people  that this two flashcarts works with the ntrboot (i dont know how)

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Juanito9001** [comment]
![20170822_160543](https://user-images.githubusercontent.com/27431883/29587551-efa72660-8753-11e7-898d-9e85f1f4f389.jpg)
![20170822_160532](https://user-images.githubusercontent.com/27431883/29587567-f7381042-8753-11e7-8dc9-973eefc3b506.jpg)
![fb_img_1503432873892](https://user-images.githubusercontent.com/27431883/29587589-06ba2be0-8754-11e7-98f9-a5cbcad52cfc.jpg)

**Comment by hedgeberg** [comment]
@Juanito9001 please don't submit your cards in other cards' threads. We're trying to keep this sorted, we've asked you a lot of times. We appreciate the attempt to contribute but its not that complicated. These cards arent the same and shouldnt be discussed in the same thread.

**Comment by hedgeberg** [comment]
Also, no, we cannot just "force" the flasher to flash the cart it doesn't work like that. If we knew how to flash it it would already be supported. Each cart has different commands needed, different memory layouts, etc. If we tried to just flash your card like a different card it would just brick, and likely become unflashable. 

Can you remove the casing on your cart so that we can get cleaner pics of the circuit board?

**Comment by Juanito9001** [comment]
@hedgeberg when you refeer to the casing, you mean the 3ds or the case of the cart? Or the sd?

**Comment by Juanito9001** [comment]
![1503436815744157029911](https://user-images.githubusercontent.com/27431883/29588099-d97efc58-8755-11e7-9c61-3c6d197f13d1.jpg)
![1503436854688-1712034760](https://user-images.githubusercontent.com/27431883/29588116-ec8e5a50-8755-11e7-9b3a-510824971304.jpg)

![1503436764371271887598](https://user-images.githubusercontent.com/27431883/29588072-bf3af7d4-8755-11e7-85f9-8d8dac42c7f8.jpg)

**Comment by hedgeberg** [comment]
@Juanito9001 i didnt ask for your cart please stop submitting in this thread they aren't the same.

**Comment by sergiogamboa2** [comment]
Yes Hedgeberg this are the photos you requested. Thank you for explaining the ''forceflash'' it cannot be done.
Bigger Chip says 120620
The small one says FIDELIX 25Q16A-501A1 (Line break) SCA114129 (line Break) 1233

![img_0711](https://user-images.githubusercontent.com/24198611/29589336-27685ce2-8752-11e7-86bd-333e8a833061.JPG)
![img_1724](https://user-images.githubusercontent.com/24198611/29589339-27a8a6e4-8752-11e7-9e2c-29756d00b79e.JPG)
![img_7345](https://user-images.githubusercontent.com/24198611/29589338-27a81efe-8752-11e7-830a-7882f8bc42ca.JPG)

**Comment by kitling** [comment]
On top of that, a 'force flash' isn't possible simply because we do not know the relevant commands, so a 'force flash' would likely end with no changes whatsoever.

**Comment by dark-samus** [comment]
this is a duplicate cart, (see issue #3 ) please check other issues before posting one.
