### ISSUE TITLE
R4iGold Wood (r4igold.cc)

### ISSUE THREAD

**Issue by Juanito9001** [kitling/flashcart_core#23]
Ok... following the suggestions of @hedgeberg , i gonna post this flashcart, i didn't saw it in other issues (except in EOL) and i gonna refeer only to this flashcart, i tried the ntrboot and it shows:
ChipID: 00000FC2
HWrev: A5A5A5A5
Here some photos and trying to be specific, it seems to have a revision, in the photo near to the pins, there's a B, other words, revision B (i dont think thats relevant, but i think is one of the hundred of clones of the R4 gold 3ds rts from r4ids.cn)
![fb_img_1503447017166](https://user-images.githubusercontent.com/27431883/29593644-2dde25ec-8771-11e7-9543-c8b2c507a9a7.jpg)
![fb_img_1503432873892](https://user-images.githubusercontent.com/27431883/29593657-58c77664-8771-11e7-811e-369bfc640289.jpg)
![20170822_160543](https://user-images.githubusercontent.com/27431883/29593672-69a47536-8771-11e7-8b3a-d537fccc8c7b.jpg)

**Comment by dark-samus** [comment]
any updaters, kernel files, etc.? Also, isn't this like the 3rd time you've opened an issue for this cart? Please keep it to one issue.

**Comment by Juanito9001** [comment]
I have, everything (unplpading it right now), but i know the firmware updaters.nds are not very useful, maybe extracting it with the Gm9 directly from the flashcart will be more useful??

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Juanito9001** [comment]
[GoldccWood_6.2_patch.rar.zip](https://github.com/kitling/flashcart_core/files/1246232/GoldccWood_6.2_patch.rar.zip)
here they are (the Rars of the Kernel and the firmware updater. nds)
like i said before, i know the .nds is the commercial firmwara, for taht reason i want to extract the ROM with GM9, bou i dont know how do that, any tutorial or guide for that?

Pd: i know too this isn't the first time i opened an issue... but the issues i open thy are for different flashcarts, because i want to help in this proyect... also, here in colombia, all the falshcarts that i post, are the Most sold... and they are the only flashcarts available in the country. thats the reason because i opened many issues with different flashcarts (R4iSDH.COM Family, R4iSDHC.HK, and R4iGOLD.CC )

**Comment by Valeri0p** [comment]
Dump 3DS / NDS / DSi type retail game cartridges: Insert the cartridge and take a look inside the C: drive. You may also dump private headers from 3DS game cartridges.

From gm9 readme

**Comment by Juanito9001** [comment]
i extracted Two files... the trim. nds and the not trim.nds
the bad news is each file occups 64mb and the page only supports 10mb files... https://mega.nz/#!IfQTCB7b!lV4A-JxBlOgTARty6cVpWCl3wPNkvBqVc1bSGofkw3A

so... here is the link with the archives i extracted with the GM9 from the flashcart

**Comment by dark-samus** [comment]
seems we now support this card (no release yet) so I'll be closing this issue.

**Comment by Juanito9001** [comment]
Tell me something... @dark-samus, the support is for a ntrboot posted in pther issue recently... yes??? In the issue r4infinity.com... in the final... yes???

_Enviado desde mi Samsung SM-G610M usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Juanito9001** [comment]
@dark-samus effectively, I test this card with a ntrboot that I found in "
Infinity 3 i R4 (http://www.r4infinity.com, updates that flash the chip available) ", i do the ntrboot and works perfectly, and the restore works too.

**Comment by Juanito9001** [comment]
![1503805993891-1677217203](https://user-images.githubusercontent.com/27431883/29746993-626062ce-8ab1-11e7-94e7-c049eabc1275.jpg)

![20170826_224939](https://user-images.githubusercontent.com/27431883/29746992-50e743a0-8ab1-11e7-8978-e82b822e2af4.jpg)

![20170826_224721](https://user-images.githubusercontent.com/27431883/29746990-40525476-8ab1-11e7-98a8-5e86948d8af8.jpg)
![20170826_224755](https://user-images.githubusercontent.com/27431883/29746979-307c3166-8ab1-11e7-8c05-3d1a62b158fd.jpg)

@kitling here is the proof, and if you see the comment of dark-samus, it says that this card is now supported, before the ntrboot 0.1.3 was released
@Hikari-chin hey, this flashcart is compatible too, so i think is  to post it in the readme of the ntrboot

**Comment by dark-samus** [comment]
ugh. @Juanito9001 yes, I said there was *no release yet* 0.1.3 *was* the release for supporting those carts. We KNOW they are supported and are working on updating the readme. Please stop commenting on issues unless you have something *constructive* to add
