### ISSUE TITLE
R4i Ultra (r4ultra.com) - AK2i rebrand

### ISSUE THREAD

**Issue by Hikari-chin** [kitling/flashcart_core#24]
This cart should be fairly easy to support, it is apparently simply a rebranding of the AK2i HW81 by the Acekard team. The cart commands seem to be the exact same; Decrypt9 detects it as an AK2i HW81 and you can even ["convert" it to an AK2i by flashing an AK2i ROM dump to it](https://gbatemp.net/threads/how-to-convert-an-r4i-ultra-r4ultra-com-clone-into-a-legit-acekard-2i-using-a-hacked-3ds.473764/). Apparently, ntrboot works if you "convert" the cart and then inject, but does not if you try to inject with the original flash intact.

[This](https://mega.nz/#!gx4kETBD!7ykQ0yXsfNTII3rxNIU1FA-JQu2DIg42D4K6geIYdlA) is claimed to be a dump of the original flash, and [this](https://my.mixtape.moe/veojmn.nds) is a dump of the ROM it uses to fool the system. 

![A picture of the cart, for clarity](https://gbatemp.net/attachments/r4i-ultra-2-jpg.1887/)

**Comment by Juanito9001** [comment]
Only with this flashcart can you do this?? Maybe with another model of R4??

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DiamondMinerITA** [comment]
@Hikari-chin can you send a photo of the pcb?

**Comment by hedgeberg** [comment]
@DiamondMinerITA fyi @Hikari-chin is a well known member of the luma support team, she deliberately did not submit the cart info because it was not needed, as it is a clone of the Ak2i HW81, as stated. If it can be "converted" then that means that, likely, its a chip id/hw rev thing in flash that gets patched. @Hikari-chin try patching the flasher's checks for ak2i to include your hw rev/chip id pair and see if you can read from the flash correctly?

**Comment by dark-samus** [comment]
the flasher detects ak2is purely based on cart commands it responds to, so those checks are null and void.

**Comment by hedgeberg** [comment]
Ah, was not aware at this point, good 2 know. Hard to guess why it wouldnt support this card until after patching unless the firmware patch changes commands, which makes this a tad more difficult.

**Comment by s1cp** [comment]
As stated before on #cakey, I restored the original R4i Ultra's flash using ntrboot_flasher, and then injected ntrboot to the original flash, which worked flawlessly.
The interesting part is that if you try to restore an ak2i's flash to it using ntrboot_flasher, it gets stuck at around chunks 30-40, but it can restore the original R4i Ultra flash just fine.
The "conversion" method of restoring an ak2i's flash to it only works on Decrypt9 so far.

**Comment by Hikari-chin** [comment]
Thank you, @s1cp!
