### ISSUE TITLE
Infinity 3 i R4 (http://www.r4infinity.com, updates that flash the chip available)

### ISSUE THREAD

**Issue by jacwib** [kitling/flashcart_core#26]
Updates: http://www.r4infinity.com/down_3.asp

Im running the latest version (i hope), will provide gm9 dump if asked, unsure about legality tho so im not just immediately uploading it here.

![img_20170824_201004](https://user-images.githubusercontent.com/2979581/29681662-b46493d8-8908-11e7-9004-cb97ba7460d6.jpg)
![img_20170824_201010](https://user-images.githubusercontent.com/2979581/29681663-b465dd24-8908-11e7-8ddb-2cc1ab07dce8.jpg)
![img_20170824_200158](https://user-images.githubusercontent.com/2979581/29681660-b462cf8a-8908-11e7-97cf-9bb4be6120da.jpg)
![img_20170824_200202](https://user-images.githubusercontent.com/2979581/29681661-b463491a-8908-11e7-8ce8-23034be7d80f.jpg)
![img_20170824_200452](https://user-images.githubusercontent.com/2979581/29681664-b469928e-8908-11e7-8a85-325dd4c0e627.jpg)
![img_20170824_200635](https://user-images.githubusercontent.com/2979581/29681665-b46c9e66-8908-11e7-8434-589b6e9a3bf8.jpg)

**Comment by hedgeberg** [comment]
This looks to be functionally the same cart to my R4i, the one we based initial R4i RTS support off of. There's a chance it is supported in its current form, but i dont know how safe it would be to test. Are you willing to risk your cart a bit? If so I can walk you through the test.

**Comment by jacwib** [comment]
sure, i've got nothing better to do. bring it on!

**Comment by hedgeberg** [comment]
It's probably better to discuss here, but I do have discord. You can find me in the reswitched discord (the switch hacking team me and other folks here are in) using this link: https://discord.gg/DThbZ7z nickname is the same.

Anyway, the first thing we'll need you to do is test to ensure you can build the flasher from source. Build deps are basically the same as modern Luma, so there are details on how to set that up over there. Can you get a working build environment and we'll keep going from there? If you have questions on that step feel free to pm me on discord.

**Comment by jacwib** [comment]
sure, ill try to get something up and running. pming you + putting a message here so the public can know my(/your) progress when im done

**Comment by jacwib** [comment]
progress!
![img_20170824_220431](https://user-images.githubusercontent.com/2979581/29686175-4e483f22-8918-11e7-85ef-4b26f899719d.jpg)

**Comment by jacwib** [comment]
have fun
[backup.zip](https://github.com/kitling/flashcart_core/files/1250108/backup.zip)

**Comment by hedgeberg** [comment]
So, for those wondering what happened, we patched the check to see if we could get dumping working on this cart. By changing the HW rev checked for in the r4i cpp object, we managed to get it to "dump" but we havent checked the dump for accuracy or similarity.

**Comment by jacwib** [comment]
but hey it dumped! thats a thing

**Comment by dark-samus** [comment]
hedge asked me to build this for you, so here you go :) 
[ntrboot_flasher.zip](https://github.com/kitling/flashcart_core/files/1250154/ntrboot_flasher.zip)

**Comment by jacwib** [comment]
gm9 has booted! all systems go
(injection works!)

**Comment by dark-samus** [comment]
sweet! Closing...
