### ISSUE TITLE
R4i Gold 3DS Rev. 9 (r4ids.cn) Compatibility

### ISSUE THREAD

**Issue by NekoMichi** [kitling/flashcart_core#28]
I have a revision 9 R4i Gold 3DS (r4ids.cn) flash cartridge that doesn't seem to be recognised by the NTRBoot Flasher. Could this model be supported, or is it not possible?

When attempting to dump using version 0.1.2 of NTRBoot Flasher, the following error is displayed:
Dumping flash
ChipID: 00000FC2
HW Rev: A6A6A6A6
Supported cartridge not detected!

The cartridge was purchased in early 2012, the front label looked like this:
![Label](https://i.imgur.com/XPOa3OG.jpg)

And the internal chip looks like this:
![Chip](http://i.imgur.com/VKhvIlX.jpg)

Not sure if useful, but this is the other side of the chip:
![ChipOther](http://i.imgur.com/a1ZlJ8g.jpg)

The flash cart runs on the Wood AKMenu 1.64 downloaded from r4ids.cn and supports RTS even though it doesn't say so on the label. When originally purchased, it had a halo/winged icon with DORASU as the publisher, but the cartridge has since been updated to display the Konami game icon instead. While revision 9 is printed on the chip board, the Wood settings menu shows "HW: R4i Gold 3DSa".

When viewed in GodMode9, it shows 2 files:
QMATERIAL_CQFJA4_00.nds (32.0 MB)
QMATERIAL_CQFJA4_00.trim.nds (30.3 MB)

Would it be possible to support this variant of the R4i Gold 3DS in the future, or is it not compatible?

**Comment by dark-samus** [comment]
tbh, I think it's just not passing the HW rev check. It's probably simple to support this one. 
[ntrboot_flasher.zip](https://github.com/kitling/flashcart_core/files/1250099/ntrboot_flasher.zip)

try dumping flash with this build. It should, in theory, dump the flash just fine. If it works I'll have you test injecting ntrboot.

**Comment by NekoMichi** [comment]
Thanks for the quick response.
The build dumped the flash perfectly.

**Comment by dark-samus** [comment]
could you please post the dumped flash?

**Comment by NekoMichi** [comment]
Here it is:
[backup.bin.zip](https://github.com/kitling/flashcart_core/files/1250113/backup.bin.zip)

**Comment by dark-samus** [comment]
alright, try this: 
[ntrboot_flasher.zip](https://github.com/kitling/flashcart_core/files/1250134/ntrboot_flasher.zip)

Attempt to flash ntrboot with this please :)

**Comment by NekoMichi** [comment]
Dump, inject, and restore all successful.
Thank you for the help!

**Comment by dark-samus** [comment]
awesome :D

**Comment by DiamondMinerITA** [comment]
@dark-samus why all those chipIDs Are 00000FC2?
Are they compatible with eachother?

**Comment by jacwib** [comment]
maybe, im gonna test mine as soon as a new build is done

**Comment by dark-samus** [comment]
@DiamondMinerITA I've explained several times that 0xFC2 is a very very common chipID. All the chipID does is give the console some information about the type of chip it's using.

**Comment by NekoMichi** [comment]
Yes, I was able to launch SafeB9SInstaller with the magnet method using the flashed cartridge.

**Comment by dark-samus** [comment]
sweet!

**Comment by DiamondMinerITA** [comment]
Wow, ur so lucky
