### ISSUE TITLE
R4tt (Probably R4 SDHC clone) from r4tt.com (NW)

### ISSUE THREAD

**Issue by Damin72** [kitling/flashcart_core#36]
This cartridge bought in some Turkish-shop (Obviosly in Turkish).
Link for kernel: http://down.r4town.com/r4itt_V5.01.rar

ChipID: 00000FC2
HW Revision: 2A2A2A2A

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

http://imgur.com/a/lNAT2

</p></details> 

GM9 Untrimmed Dump: 
https://drive.google.com/open?id=0B9vr_WZsN50DUVJfMkZtMVZpTkE

**Comment by dark-samus** [comment]
this seems to be a clone of the cart in #3 please take all additional comments/concerns there. Thanks :)
