### ISSUE TITLE
R4i ultra (www.r4ids.cn)

### ISSUE THREAD

**Issue by lbc493** [kitling/flashcart_core#49]
I have a friend with r4i ultra whose web page is www.r4ids.cn not www.r4ultra.com. Ntrboothax can be instaled on this one?

**Comment by dark-samus** [comment]
hi, can you please read the readme? We need more information than "it came from here" to be able to provide support. Thanks.

**Comment by Hikari-chin** [comment]
Issue template wasn't filled out; closed.
