### ISSUE TITLE
R4i SDHC Wifi no 3DS(r4i-sdhc.com)

### ISSUE THREAD

**Issue by JollyMaster** [kitling/flashcart_core#55]
R4i SDHC Wifi (r4i-sdhc.com)

 

http://www.r4i-sdhc.com/R4i%20V1.84b%20English.zip

I can dump and flash. But when injected NTR stops at 99%

ChipID: 00000FC2
HW Revision: 00000000

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

 

http://i.imgur.com/VyU6UKx.jpg

http://i.imgur.com/dzYC3lu.jpg

http://i.imgur.com/hW03rga.jpg

http://i.imgur.com/OLCfGxS.jpg

http://i.imgur.com/hK1ZPgj.jpg

http://i.imgur.com/EdWpAe8.jpg

</p></details> 

GM9 Untrimmed Dump: https://ufile.io/6z7ky

**Comment by ShadixAced** [comment]
The model you've showed is a R4 Upgrade Revolution for DS (WiFi) from r4i-sdhc,com, not a R4i card.

If he could read it, seems that it's a kind of DSTT clone. Or else he would have rejected the card. (not sure now about manual utilisation). If that's the case, you will need to see Hikari-chin's DSTT gist and see if your PCB (SST something as I've saw) is supported.

**Comment by JollyMaster** [comment]
with DSTT dumps and resets, but when I try to inject it it blocks 99%. I also tried with the new b9s 30kb but it still does not work. can you give me a straight?

**Comment by ShadixAced** [comment]
May have found your ID  = 0x80BF
So normally it *should* work, but seems that you cannot make it through the injection.

**Comment by dark-samus** [comment]
could you provide the file on the sdcard ntrboot/backup.bin so we can examine it? Also, which cart are you selecting from the menu to get the dump?

**Comment by JollyMaster** [comment]
here is the dump [Link Mega](https://mega.nz/#!mU1ynDJK!Jx4LPCAvfri9j970rCUFDG_1_iw-91qrvpkLfrSTJAU)
I managed to restore it with dsttflashwriter. 
grazie per la pazienza

**Comment by JollyMaster** [comment]
dump dstt card

**Comment by dark-samus** [comment]
closing this. Take further comments/questions to #56
