### ISSUE TITLE
R4 SDHC GOLD PRO RTS 2017 (www.r4isdhc.com)

### ISSUE THREAD

**Issue by ScouserCL** [kitling/flashcart_core#57]
ChipID: 302241E3
HW Revision: 9856448A

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

<a href="https://imgur.com/Sh1S1uJ"><img src="https://i.imgur.com/Sh1S1uJt.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/MCIQKVN"><img src="https://i.imgur.com/MCIQKVNt.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/6ujuukw"><img src="https://i.imgur.com/6ujuukwt.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/6EZYjR9"><img src="https://i.imgur.com/6EZYjR9t.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/Sic9xsI"><img src="https://i.imgur.com/Sic9xsIt.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/EVtwm1s"><img src="https://i.imgur.com/EVtwm1st.jpg" title="source: imgur.com" /></a>
<br>
Click to enlarge

</p></details> 

GM9 Untrimmed Dump: None
Website: http://www.r4isdhc.com/
Kernel: http://www.r4isdhc.com/2014-r4isdhc-gold-pro/

**Comment by dark-samus** [comment]
duplicate.

**Comment by Juanito9001** [comment]
No, he means it's a duplicate from this #11
