### ISSUE TITLE
R4i unlimited upgradable Revolution for Ds (WWW.R4I-SDHC.HK)

### ISSUE THREAD

**Issue by lomejor18** [kitling/flashcart_core#58]
ChipID: 00000FC2
HW Revision: 00000000

Kernel:
http://www.r43ds.org/downloads/r4i3dsunlimup/r4i-english-r4i-sdhc-hk.zip

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

Cartridge and PCB:

![front](https://user-images.githubusercontent.com/24194552/30229870-b4046d46-94b1-11e7-9174-95459f1ba069.jpg)
![board1](https://user-images.githubusercontent.com/24194552/30229868-b3f9edda-94b1-11e7-8f4e-ffcfa6534d3d.jpg)
![board2](https://user-images.githubusercontent.com/24194552/30229869-b3fa00d6-94b1-11e7-860a-f67320183e89.jpg)

Game title:

![screen1](https://user-images.githubusercontent.com/24194552/30229871-b405549a-94b1-11e7-8471-f090f9bab501.jpg)

UI:

![ui](https://user-images.githubusercontent.com/24194552/30229873-b41665aa-94b1-11e7-9b08-1a693173a65d.jpg)

Godmode screenshot:

![screen2](https://user-images.githubusercontent.com/24194552/30229872-b40ff198-94b1-11e7-9c76-e97798602cd7.jpg)

</p></details> 

GM9 Untrimmed Dump: 
[SPONGEBOB AP_AL3E78_00.zip](https://github.com/kitling/flashcart_core/files/1289034/SPONGEBOB.AP_AL3E78_00.zip)

**Comment by dark-samus** [comment]
this looks a lot like a dstt clone...

**Comment by DiamondMinerITA** [comment]
It is, i have the same identical menu on my dstt clone.
Plus, there's the nand chip.
The sticker it's pretty much my sticker with different colors

**Comment by lomejor18** [comment]
@DiamondMinerITA do you believe there's hope for us? or is a long shot?

**Comment by dark-samus** [comment]
since this is a DSTT clone, I'll be closing this one, please take further comments to #56

**Comment by Josem199518** [comment]
necesito ayuda con esta r4
