### ISSUE TITLE
M3DS Real (m3adapter.com)

### ISSUE THREAD

**Issue by tonyrayo** [kitling/flashcart_core#62]
ChipID: 00000FC2
HW Revision: 46464646
^values for v1/FPGA version, v2 coming soon

Everyone's favorite flash cart is finally here! (hush crickets)  Special thanks to GBATemp user _Emmo for providing, well, basically all of this data (N3DS arrives today, however it's on 11.5.0 and hardmod won't happen until next week).  Please pardon the lens flair on the reverse PCB image (thankfully the few traces there aren't incredibly important).

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![slot01_m3r](https://user-images.githubusercontent.com/416528/30240836-e6b1909a-9545-11e7-83f0-f2cc3600b0f1.png)
![front_aka_back](https://user-images.githubusercontent.com/416528/30240837-ec1312de-9545-11e7-9aab-941ae54f7c07.png)
![back_aka_front](https://user-images.githubusercontent.com/416528/30240840-ef2c6dbc-9545-11e7-9dcd-5ac3c11756ef.png)

</p></details> 

GM9 Untrimmed Dump: 
[PASSCARD3____AMFE01_00.zip](https://github.com/kitling/flashcart_core/files/1289855/PASSCARD3____AMFE01_00.zip)

**Comment by HandsomeMatt** [comment]
I believe the M3DS Real, M3i Zero and the M3i Zero GMP-Z003 all share the same firmware - M3 Sakura. I think they're clones or the same family.

**Comment by Emmoooo** [comment]
Glad to help with this card, thanks for the mention!
My M3DS Real has another PCB though, pictures below.
![img_2983](https://user-images.githubusercontent.com/31800662/30241860-11f07c62-958c-11e7-88e5-c4dfa235abaa.JPG)
![img_2984](https://user-images.githubusercontent.com/31800662/30241862-1223cbee-958c-11e7-814a-1d67db231627.JPG)
![img_2985](https://user-images.githubusercontent.com/31800662/30241861-1223c55e-958c-11e7-82ed-c5fb032c2434.JPG)

**Comment by tonyrayo** [comment]
History of the M3 Line (will be changed/corrected as needed):

Common Name | Description | Supported Firmware | Notes
----------- | ----------- | ------------------ | -----
M3DS Simply | A 1:1 clone of the original R4 | Wood R4 | 2GB max card limit
M3DS Real | Upgraded G6DS Real (microSD instead of NAND) | TouchPod, Sakura, WoodM3, YsMenu | 2 varients

**Comment by kitling** [comment]
Does this cart have firmware upgrades as well as kernel upgrades? I thought it didn't.

**Comment by dark-samus** [comment]
the first variant looks like it can't be updated. The second variant looks a lot like the M3i zero

**Comment by Emmoooo** [comment]
@kitling You're right, I searched for something but couldn't find any upgrades for this one unfortunately.

**Comment by tonyrayo** [comment]
@kitling There is a base kernel that is needed for this cart (afaik it never received an upgrade, but I will try to verify this).

@dark-samus I'm calling the cart with the FPGA v1 (as it seems to have been released first) and the FPGAless board v2.  Both have DLDI support, so I'm hoping that inclusion/lack of FPGA (I can guess at what this was for but I have zero code to back anything up) doesn't change its usability for our purposes.

**Comment by kitling** [comment]
So, the ability to update the title/icon the cart shows on boot is roughly (not exactly) equivalent to the ability to install ntrboot. If we cannot do the former, we almost certainly won't be able to do the latter.

**Comment by Oleboy555** [comment]
![m3](https://user-images.githubusercontent.com/24965670/30284189-85229cd0-971a-11e7-8522-13694d1b321b.jpg)

this is what my m3ds real looks like

**Comment by Flauscheloni** [comment]
My PCB looks like the one from @Emmoooo, also 2007.11.30  
I have a second one but I can't find it right now.  
Is there anything I can do to help?

**Comment by kitling** [comment]
Closing, as we don't have any evidence of what is needed.

Feel free to comment and I'll reopen if any evidence is actually found.
