### ISSUE TITLE
White 2017 R4i dual-core (r4isdhc.com)

### ISSUE THREAD

**Issue by SamTorr** [kitling/flashcart_core#63]
You can help me flash with ntrboot, this is the r4 I own.

Please and thank you

![r4](https://user-images.githubusercontent.com/32022814/30515716-4bf437a6-9aea-11e7-9546-455d7e384849.PNG)

**Comment by SamTorr** [comment]
this is the kernel: [Download](http://www.r4isdhc.com/KerneDownload/R4i-V3.9b%20Spanish.zip)

**Comment by knowbeard** [comment]
This one is currently being worked on, it says so in the readme - we just have to be patient we have no idea how low it will take afaik.

**Comment by dark-samus** [comment]
duplicate.

**Comment by SamTorr** [comment]
I just have to wait then, or apply hardmode
