### ISSUE TITLE
2016 R4i dual-core (r4isdhc.com)

### ISSUE THREAD

**Issue by simplyphat** [kitling/flashcart_core#67]
kernel link: www.r4isdhc.com/r4-download/
ChipID: unknown
HW Revision: unknown
<details><summary>Images <em>(Click to Expand)</em></summary><p> 
![img_4585](https://user-images.githubusercontent.com/32116075/30623306-05203708-9d74-11e7-87e7-e5a198571e56.JPG)
![img_4586](https://user-images.githubusercontent.com/32116075/30623305-051e0ad2-9d74-11e7-87b8-d2d07eb1e366.JPG)
![img_4587](https://user-images.githubusercontent.com/32116075/30623308-0521463e-9d74-11e7-82c2-afb88490bece.JPG)
![img_4588](https://user-images.githubusercontent.com/32116075/30623307-05208eb0-9d74-11e7-91c8-019d0889a77c.JPG)
</p></details> 
GM9 Untrimmed Dump: [r4.zip](https://github.com/kitling/flashcart_core/files/1316358/r4.zip)

**Comment by dark-samus** [comment]
duplicate.
