### ISSUE TITLE
2DSTT CARDS

### ISSUE THREAD

**Issue by Zootexxx** [kitling/flashcart_core#69]
are these 2 DSTT ever gonna be supported

DSTT Flash Checker 0.01
ST MW28W160(B)B
Good!! (^^)v

and 

DSTT Flash Checker 0.01
INTEL 28F320B3T
Good!! (^^)v

i have both

**Comment by HandsomeMatt** [comment]
Congrats on missing the DSTT thread. Perhaps try running the DSTT
implementation and telling us if it works or not, and then provide your log
file.

**Comment by kitling** [comment]
https://github.com/kitling/flashcart_core/issues/56
