### ISSUE TITLE
R4i SDHC Dual-Core 2017 (r4isdhc.com)

### ISSUE THREAD

**Issue by Oldsx** [kitling/flashcart_core#74]
Firmware update: http://www.r4isdhc.com/2014-r4isdhc-dual-core/

Any information: http://www.r4isdhc.com/r4-product/
    
ChipID: (I don't know it)
HW Revision: (I don't know it) 

Images: (retro) https://postimg.org/image/6y3tn9h39n/db40cf7f/

(front)
https://postimg.org/image/1mox2jrl57/451ac3f9/

GM9 Untrimmed Dump: https://openload.co/f/FoOQhs7etO0/BOMBERMANLND_ABXK01_00.nds

**Comment by NoMod-Programming** [comment]
If this can be re-opened, I also have one of these (it says 2014 on the label, but they appear to be the same card). I'd like to get this working, if it's possible.
