### ISSUE TITLE
R4 SDHC 3DS DSI 2014 Dual Core (www.r4isdhc.com.cn)

### ISSUE THREAD

**Issue by nsuchy** [kitling/flashcart_core#79]
This is a request for flashcart_core to support the R4 SDHC 3DS DSI 2014 Dual Core (http://www.r4isdhc.com.cn)

ChipID: Not sure how to get.
HW Revision: Not sure how to get.

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![ou3kxchp](https://user-images.githubusercontent.com/8227641/31469034-43049cd0-aeae-11e7-9103-a2782288e3b7.jpg)
![ynjaycq-](https://user-images.githubusercontent.com/8227641/31469035-43187e26-aeae-11e7-865b-cf037e325946.jpg)
![zcb41egi](https://user-images.githubusercontent.com/8227641/31469036-432afb14-aeae-11e7-8f2e-49b67b9b0a81.jpg)

</p></details> 

**Notes:**
The website appears to be closely associated with r4isdhc.com.

**GM9 Untrimmed Dump:** Unable to provide as I don't have CFW. However the file below is the "kernel" that their website providers users with.
[wood-v162.rar.zip](https://github.com/kitling/flashcart_core/files/1377345/wood-v162.rar.zip)

On a sidenote: I see the file: https://github.com/kitling/flashcart_core/blob/master/devices/r4sdhc_dualcore.cpp however I'm not sure if it'd support this cart.

**I am willing to be a tester for support of this cart**

**Comment by kitling** [comment]
That source is for the r4isdhc.hk carts. If this is related to the r4isdhc.com/r4i-sdhc.com carts, then we are making progress on those carts.

**Comment by nsuchy** [comment]
@kitling So to confirm this card is basically identical and will most likely work with it? I want to play with NTRBootHax and appreciate what the homebrew community is doing.

**Comment by kitling** [comment]
@nsuchy *If* this is related. I give no such guarantees. Feel free to look at the PCBs of the other carts and figure that out for yourself.

**Comment by nsuchy** [comment]
@kitling I understand, I'll check the PCBs, is that firmware file I gave you exactly the same?

**Comment by kitling** [comment]
I. Don't. Know.

In any case, what you gave me is the 'kernel', not the firmware. If it's similar to the other carts I mentioned, then that's to be expected -- they do their updates inside of their kernel.

**Comment by nsuchy** [comment]
@kitling Thank you for clarifying. If there is a .NDS file I can run to give you chip id number or anything you'd like me to test let me know.

**Comment by nsuchy** [comment]
I found this datasheet on my card if that helps http://www.datasheet4u.com/datasheet-pdf/MacronixInternational/25L1605D/pdf.php?id=689040

**Comment by trbocode** [comment]
This is an ace3ds clone iirc. Can you please try the ace3ds kernel?
BTW, I brought one two, should arrive this week.

**Comment by nsuchy** [comment]
@trbocode Sure, mind sending me a link?

**Comment by trbocode** [comment]
http://www.ace3ds.com/ace-3ds-download.html

**Comment by nsuchy** [comment]
@trbocode Downloading now and will post an update shortly. Filetrip is such a slow filehost :/

**Comment by nsuchy** [comment]
Unfortunately even after renaming _DS_MENU.DAT to _dsmenu.dat (I tried on both kernels) it would not load and showed an error message.
![img_1895 heic](https://user-images.githubusercontent.com/8227641/31546428-4810c098-aff1-11e7-85f8-9e5c0b475137.jpg)

**My working old file system. Only the flasher doesn't work.**
[Old File System.zip](https://github.com/kitling/flashcart_core/files/1382574/Old.File.System.zip)
 the card cannot load the kernel. I tried using both kernels V2.13

**Comment by nsuchy** [comment]
@trbocode ^^^

**Comment by trbocode** [comment]
The cart looks very similar to the Ace and the gateway blue card, still.

**Comment by nsuchy** [comment]
it has a very similar kernel too. That being said do you have any ideas on flashing the NTRBoot firmware to it?

**Comment by trbocode** [comment]
No.
Maybe try the gateway kernel

**Comment by nsuchy** [comment]
@trbocode Still no luck, that's why I've requested support for my specific cart.

**Comment by nsuchy** [comment]
This issue's images (https://github.com/kitling/flashcart_core/issues/33) confirms my cart is actually a relabeled Ace3ds Plus. This can be closed :)
