### ISSUE TITLE
EZ Flash V and Vi support request

### ISSUE THREAD

**Issue by Sabre8073** [kitling/flashcart_core#87]
As title states

Thx for the great work

**Comment by kitling** [comment]
Could you please provide information about the cart, like what is in the issue template? This is completely useless as-is.

**Comment by Sabre8073** [comment]
The only information I can provide for this cart is sharing this two links with information about the cart and software, because i'm not a developer.

https://gbatemp.net/threads/ez-flash-v-review.42399/
http://www.ezflash.cn/home.htm
