### ISSUE TITLE
DSTWO possibly contribution?

### ISSUE THREAD

**Issue by Legarad** [kitling/flashcart_core#96]
I would like to contribute something if possible regarding DSTWO. What is needed?

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

</p></details> 

GM9 Untrimmed Dump:

**Comment by hedgeberg** [comment]
There is already a thread for this. Ds2/2p have been heavily researched but needs significant reverse engineering to set it up. Please check for threads before opening new ones.
